/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteServidor;

import java.rmi.Naming;

/**
 *
 * @author vsnv
 */
public class ClienteDeCampamento extends javax.swing.JFrame {
    /**
     * Creates new form ClienteDeCampamento
     */
    public ClienteDeCampamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelActividades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNinoID = new javax.swing.JLabel();
        jTextFieldNinoId = new javax.swing.JTextField();
        botonConsultarActividad = new javax.swing.JButton();
        labelNumActividades = new javax.swing.JLabel();
        jTextFieldResultadoActividades = new javax.swing.JTextField();
        panelSoga = new javax.swing.JPanel();
        labelSoga = new javax.swing.JLabel();
        labelColaEsperaSoga = new javax.swing.JLabel();
        jTextFieldColaEsperaSoga = new javax.swing.JTextField();
        botonConsultarColaEsperaSoga = new javax.swing.JButton();
        labelControlDeCampamento = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelTirolina = new javax.swing.JLabel();
        labelColaEsperaTirolina = new javax.swing.JLabel();
        jTextFieldColaEsperaTirolina = new javax.swing.JTextField();
        botonConsultarColaEsperaTirolina = new javax.swing.JButton();
        labelNumUsosTirolina = new javax.swing.JLabel();
        jTextFieldNumUsosTirolina = new javax.swing.JTextField();
        botonNumUsosTirolina = new javax.swing.JButton();
        panelMerendero = new javax.swing.JPanel();
        labelMerienda = new javax.swing.JLabel();
        labelNumNinosMerendando = new javax.swing.JLabel();
        jTextFieldNumNinosMerendandoMerienda = new javax.swing.JTextField();
        botonConsultarNumNinosMerendandoMerienda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBandejasSuciasMerienda = new javax.swing.JTextField();
        botonConsultarBandejasSuciasMerienda = new javax.swing.JButton();
        labelBandejasLimpiasMerienda = new javax.swing.JLabel();
        jTextFieldBandejasLimpiasMerienda = new javax.swing.JTextField();
        botonConsultarBandejasLimpiasMerienda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelActividades.setBackground(new java.awt.Color(153, 153, 153));
        panelActividades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ACTIVIDADES");
        panelActividades.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 20));

        labelNinoID.setForeground(new java.awt.Color(0, 0, 0));
        labelNinoID.setText("ID Niño");
        panelActividades.add(labelNinoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextFieldNinoId.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNinoId.setForeground(new java.awt.Color(0, 0, 0));
        panelActividades.add(jTextFieldNinoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 100, -1));

        botonConsultarActividad.setBackground(new java.awt.Color(102, 102, 102));
        botonConsultarActividad.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultarActividad.setText("Consultar");
        botonConsultarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActividadActionPerformed(evt);
            }
        });
        panelActividades.add(botonConsultarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        labelNumActividades.setForeground(new java.awt.Color(0, 0, 0));
        labelNumActividades.setText("Número actividades");
        panelActividades.add(labelNumActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jTextFieldResultadoActividades.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldResultadoActividades.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldResultadoActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultadoActividadesActionPerformed(evt);
            }
        });
        panelActividades.add(jTextFieldResultadoActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, -1));

        mainPanel.add(panelActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 330, 180));

        panelSoga.setBackground(new java.awt.Color(153, 153, 153));
        panelSoga.setForeground(new java.awt.Color(153, 153, 153));
        panelSoga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSoga.setForeground(new java.awt.Color(0, 0, 0));
        labelSoga.setText("SOGA");
        panelSoga.add(labelSoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        labelColaEsperaSoga.setForeground(new java.awt.Color(0, 0, 0));
        labelColaEsperaSoga.setText("Cola de espera");
        panelSoga.add(labelColaEsperaSoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jTextFieldColaEsperaSoga.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldColaEsperaSoga.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldColaEsperaSoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColaEsperaSogaActionPerformed(evt);
            }
        });
        panelSoga.add(jTextFieldColaEsperaSoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 260, -1));

        botonConsultarColaEsperaSoga.setBackground(new java.awt.Color(102, 102, 102));
        botonConsultarColaEsperaSoga.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultarColaEsperaSoga.setText("Consultar");
        botonConsultarColaEsperaSoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarColaEsperaSogaActionPerformed(evt);
            }
        });
        panelSoga.add(botonConsultarColaEsperaSoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        mainPanel.add(panelSoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 420, 180));

        labelControlDeCampamento.setForeground(new java.awt.Color(0, 0, 0));
        labelControlDeCampamento.setText("CONTROL DE CAMPAMENTO");
        mainPanel.add(labelControlDeCampamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTirolina.setForeground(new java.awt.Color(0, 0, 0));
        labelTirolina.setText("TIROLINA");
        jPanel1.add(labelTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        labelColaEsperaTirolina.setForeground(new java.awt.Color(0, 0, 0));
        labelColaEsperaTirolina.setText("Cola de espera");
        jPanel1.add(labelColaEsperaTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextFieldColaEsperaTirolina.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldColaEsperaTirolina.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldColaEsperaTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 80, -1));

        botonConsultarColaEsperaTirolina.setBackground(new java.awt.Color(102, 102, 102));
        botonConsultarColaEsperaTirolina.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultarColaEsperaTirolina.setText("Consultar");
        botonConsultarColaEsperaTirolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarColaEsperaTirolinaActionPerformed(evt);
            }
        });
        jPanel1.add(botonConsultarColaEsperaTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 90, -1));

        labelNumUsosTirolina.setForeground(new java.awt.Color(0, 0, 0));
        labelNumUsosTirolina.setText("Número de usos");
        jPanel1.add(labelNumUsosTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTextFieldNumUsosTirolina.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumUsosTirolina.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextFieldNumUsosTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 80, -1));

        botonNumUsosTirolina.setBackground(new java.awt.Color(102, 102, 102));
        botonNumUsosTirolina.setForeground(new java.awt.Color(255, 255, 255));
        botonNumUsosTirolina.setText("Consultar");
        botonNumUsosTirolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNumUsosTirolinaActionPerformed(evt);
            }
        });
        jPanel1.add(botonNumUsosTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 90, -1));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 420, 180));

        panelMerendero.setBackground(new java.awt.Color(153, 153, 153));
        panelMerendero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMerienda.setForeground(new java.awt.Color(0, 0, 0));
        labelMerienda.setText("MERIENDA");
        panelMerendero.add(labelMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        labelNumNinosMerendando.setForeground(new java.awt.Color(0, 0, 0));
        labelNumNinosMerendando.setText("Niños merendando");
        panelMerendero.add(labelNumNinosMerendando, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jTextFieldNumNinosMerendandoMerienda.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNumNinosMerendandoMerienda.setForeground(new java.awt.Color(0, 0, 0));
        panelMerendero.add(jTextFieldNumNinosMerendandoMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 70, -1));

        botonConsultarNumNinosMerendandoMerienda.setBackground(new java.awt.Color(102, 102, 102));
        botonConsultarNumNinosMerendandoMerienda.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultarNumNinosMerendandoMerienda.setText("Consultar");
        botonConsultarNumNinosMerendandoMerienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarNumNinosMerendandoMeriendaActionPerformed(evt);
            }
        });
        panelMerendero.add(botonConsultarNumNinosMerendandoMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 80, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bandejas sucias");
        panelMerendero.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTextFieldBandejasSuciasMerienda.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBandejasSuciasMerienda.setForeground(new java.awt.Color(0, 0, 0));
        panelMerendero.add(jTextFieldBandejasSuciasMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 80, -1));

        botonConsultarBandejasSuciasMerienda.setBackground(new java.awt.Color(102, 102, 102));
        botonConsultarBandejasSuciasMerienda.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultarBandejasSuciasMerienda.setText("Consultar");
        botonConsultarBandejasSuciasMerienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarBandejasSuciasMeriendaActionPerformed(evt);
            }
        });
        panelMerendero.add(botonConsultarBandejasSuciasMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 80, -1));

        labelBandejasLimpiasMerienda.setBackground(new java.awt.Color(0, 0, 0));
        labelBandejasLimpiasMerienda.setForeground(new java.awt.Color(0, 0, 0));
        labelBandejasLimpiasMerienda.setText("Bandejas limpias");
        panelMerendero.add(labelBandejasLimpiasMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTextFieldBandejasLimpiasMerienda.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldBandejasLimpiasMerienda.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldBandejasLimpiasMerienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBandejasLimpiasMeriendaActionPerformed(evt);
            }
        });
        panelMerendero.add(jTextFieldBandejasLimpiasMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 80, -1));

        botonConsultarBandejasLimpiasMerienda.setBackground(new java.awt.Color(102, 102, 102));
        botonConsultarBandejasLimpiasMerienda.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultarBandejasLimpiasMerienda.setText("Consultar");
        botonConsultarBandejasLimpiasMerienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarBandejasLimpiasMeriendaActionPerformed(evt);
            }
        });
        panelMerendero.add(botonConsultarBandejasLimpiasMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 80, -1));

        mainPanel.add(panelMerendero, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 330, 180));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActividadActionPerformed
        try{
            String respuesta = "";
            InterfaceCampamento obj = (InterfaceCampamento) Naming.lookup("//127.0.0.1/ObjetoCampamento");
            respuesta = obj.getNumActividades(jTextFieldNinoId.getText());
            jTextFieldResultadoActividades.setText(respuesta);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonConsultarActividadActionPerformed

    private void jTextFieldColaEsperaSogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColaEsperaSogaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColaEsperaSogaActionPerformed

    private void botonConsultarBandejasSuciasMeriendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarBandejasSuciasMeriendaActionPerformed
        try{
            String respuesta = "";
            InterfaceCampamento obj = (InterfaceCampamento) Naming.lookup("//127.0.0.1/ObjetoCampamento");
            respuesta = obj.getNumBandejasSucias();
            jTextFieldBandejasSuciasMerienda.setText(respuesta);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonConsultarBandejasSuciasMeriendaActionPerformed

    private void jTextFieldBandejasLimpiasMeriendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBandejasLimpiasMeriendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBandejasLimpiasMeriendaActionPerformed

    private void botonConsultarBandejasLimpiasMeriendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarBandejasLimpiasMeriendaActionPerformed
        try{
            String respuesta = "";
            InterfaceCampamento obj = (InterfaceCampamento) Naming.lookup("//127.0.0.1/ObjetoCampamento");
            respuesta = obj.getNumBandejasLimpias();
            jTextFieldBandejasLimpiasMerienda.setText(respuesta);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonConsultarBandejasLimpiasMeriendaActionPerformed

    private void jTextFieldResultadoActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultadoActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultadoActividadesActionPerformed

    private void botonConsultarNumNinosMerendandoMeriendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarNumNinosMerendandoMeriendaActionPerformed
        try{
            String respuesta = "";
            InterfaceCampamento obj = (InterfaceCampamento) Naming.lookup("//127.0.0.1/ObjetoCampamento");
            respuesta = obj.getNumNinosMerendando();
            jTextFieldNumNinosMerendandoMerienda.setText(respuesta);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonConsultarNumNinosMerendandoMeriendaActionPerformed

    private void botonConsultarColaEsperaTirolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarColaEsperaTirolinaActionPerformed
        try{
            String respuesta = "";
            InterfaceCampamento obj = (InterfaceCampamento) Naming.lookup("//127.0.0.1/ObjetoCampamento");
            respuesta = obj.getNumNinosEsperandoTirolina();
            jTextFieldColaEsperaTirolina.setText(respuesta);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonConsultarColaEsperaTirolinaActionPerformed

    private void botonNumUsosTirolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNumUsosTirolinaActionPerformed
        try{
            String respuesta = "";
            InterfaceCampamento obj = (InterfaceCampamento) Naming.lookup("//127.0.0.1/ObjetoCampamento");
            respuesta = obj.getUsosTirolina();
            jTextFieldNumUsosTirolina.setText(respuesta);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonNumUsosTirolinaActionPerformed

    private void botonConsultarColaEsperaSogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarColaEsperaSogaActionPerformed
        try{
            String respuesta = "";
            InterfaceCampamento obj = (InterfaceCampamento) Naming.lookup("//127.0.0.1/ObjetoCampamento");
            respuesta = obj.getNumNinosColaEsperaSoga();
            jTextFieldColaEsperaSoga.setText(respuesta);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonConsultarColaEsperaSogaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteDeCampamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteDeCampamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteDeCampamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteDeCampamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteDeCampamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarActividad;
    private javax.swing.JButton botonConsultarBandejasLimpiasMerienda;
    private javax.swing.JButton botonConsultarBandejasSuciasMerienda;
    private javax.swing.JButton botonConsultarColaEsperaSoga;
    private javax.swing.JButton botonConsultarColaEsperaTirolina;
    private javax.swing.JButton botonConsultarNumNinosMerendandoMerienda;
    private javax.swing.JButton botonNumUsosTirolina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBandejasLimpiasMerienda;
    private javax.swing.JTextField jTextFieldBandejasSuciasMerienda;
    private javax.swing.JTextField jTextFieldColaEsperaSoga;
    private javax.swing.JTextField jTextFieldColaEsperaTirolina;
    private javax.swing.JTextField jTextFieldNinoId;
    private javax.swing.JTextField jTextFieldNumNinosMerendandoMerienda;
    private javax.swing.JTextField jTextFieldNumUsosTirolina;
    private javax.swing.JTextField jTextFieldResultadoActividades;
    private javax.swing.JLabel labelBandejasLimpiasMerienda;
    private javax.swing.JLabel labelColaEsperaSoga;
    private javax.swing.JLabel labelColaEsperaTirolina;
    private javax.swing.JLabel labelControlDeCampamento;
    private javax.swing.JLabel labelMerienda;
    private javax.swing.JLabel labelNinoID;
    private javax.swing.JLabel labelNumActividades;
    private javax.swing.JLabel labelNumNinosMerendando;
    private javax.swing.JLabel labelNumUsosTirolina;
    private javax.swing.JLabel labelSoga;
    private javax.swing.JLabel labelTirolina;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelActividades;
    private javax.swing.JPanel panelMerendero;
    private javax.swing.JPanel panelSoga;
    // End of variables declaration//GEN-END:variables
}
